.TH OCIODISPLAY "1" "August 2022" "ociodisplay " "User Commands"
.SH NAME
ociodisplay \- apply a colorspace conversion to an image sequence
.SH DESCRIPTION
.SS "Keys:"
.TP
Ctrl+Up:
Exposure +1/4 stop (in scene linear)
.IP
Ctrl+Down: Exposure \fB\-1\fR/4 stop (in scene linear)
Ctrl+Home: Reset Exposure + Gamma
.TP
Alt+Up:
Gamma up (post display transform)
.TP
Alt+Down:
Gamma down (post display transform)
.TP
Alt+Home:
Reset Exposure + Gamma
.TP
C:
View Color
.TP
R:
View Red
.TP
G:
View Green
.TP
B:
View Blue
.TP
A:
View Alpha
.TP
L:
View Luma
.TP
Right\-Mouse Button:
Configure Display / Transform / ColorSpace / Looks / Optimization
.IP
Esc: Quit
.PP
loading: \fB\-\-help\fR
.SS "Keys:"
.TP
Ctrl+Up:
Exposure +1/4 stop (in scene linear)
.IP
Ctrl+Down: Exposure \fB\-1\fR/4 stop (in scene linear)
Ctrl+Home: Reset Exposure + Gamma
.TP
Alt+Up:
Gamma up (post display transform)
.TP
Alt+Down:
Gamma down (post display transform)
.TP
Alt+Home:
Reset Exposure + Gamma
.TP
C:
View Color
.TP
R:
View Red
.TP
G:
View Green
.TP
B:
View Blue
.TP
A:
View Alpha
.TP
L:
View Luma
.TP
Right\-Mouse Button:
Configure Display / Transform / ColorSpace / Looks / Optimization
.IP
Esc: Quit
.PP
loading: \fB\-\-version\fR
.SH "SEE ALSO"
The full documentation for
.B ociodisplay
is maintained as a Texinfo manual.  If the
.B info
and
.B ociodisplay
programs are properly installed at your site, the command
.IP
.B info ociodisplay
.PP
should give you access to the complete manual.
